import 'dart:async';

import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'core/di/injector.dart';
import 'core/services/hive_service.dart';
import 'app.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive early for offline storage
  await Hive.initFlutter();
  await HiveService.ensureCoreBoxes();

  // Firebase init guarded to work even without real options during local dev
  try {
    // Expecting firebase_options.dart generated by FlutterFire CLI
    // If missing, this will throw and we fall back to default initialization
    // ignore: avoid_dynamic_calls
    final dynamic firebaseOptions = _tryLoadFirebaseOptions();
    if (firebaseOptions != null) {
      await Firebase.initializeApp(options: firebaseOptions);
    } else {
      await Firebase.initializeApp();
    }
  } catch (_) {
    // Continue without Firebase for local/offline work
  }

  // Dependency injection
  setupInjector(GetIt.instance);

  runZonedGuarded(
    () => runApp(const EnigmaVoiceApp()),
    (error, stack) {
      // TODO: add crash reporting if needed
    },
  );
}

Object? _tryLoadFirebaseOptions() {
  try {
    // The file is optional until Firebase is configured
    // ignore: uri_does_not_exist
    // ignore: undefined_function
    // ignore: avoid_dynamic_calls
    // ignore: unused_local_variable
    // ignore: dead_code
    return null; // Placeholder: real options will be injected once configured
  } catch (_) {
    return null;
  }
}
